version: dev{build}
image: Visual Studio 2017
configuration: Release
environment:
  matrix:
  - THIS_BUILD_IS_RECOMMENDED__VCXPROJ_BUILD: 1
  - THIS_BUILD_IS_NOT_RECOMMENDED__GCC_CMAKE_BUILD: 1
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
build:
  parallel: true
  verbosity: quiet

for:
-
  matrix:
    only:
      - THIS_BUILD_IS_NOT_RECOMMENDED__GCC_CMAKE_BUILD: 1
  build_script:
   ps: |
     mkdir build
     cd build
     $env:MSYSTEM = "MINGW32"
     $env:MSYSTEM_CARCH = "i686"
     $env:MSYSTEM_CHOST = "i686-w64-mingw32"
     $env:MSYSTEM_PREFIX = "C:/msys64/mingw32"
     $env:Path = "C:\msys64\mingw32\bin;C:\msys64\usr\local\bin;C:\msys64\usr\bin;" + $env:Path
     cmake -G"MSYS Makefiles" .. -DCMAKE_CXX_FLAGS=-w -DCMAKE_C_FLAGS=-w
     if (0 -ne $LastExitCode)
     {
         throw "Failed to execute cmake"
     }
     make -j 2
     if (0 -ne $LastExitCode)
     {
         throw "Failed to execute make"
     }
     mkdir otvdm-cmake-gcc-${env:APPVEYOR_REPO_BRANCH}-${env:APPVEYOR_BUILD_NUMBER}
     cd otvdm-cmake-gcc-${env:APPVEYOR_REPO_BRANCH}-${env:APPVEYOR_BUILD_NUMBER}
     function makedll([string]$src, [string]$name, [string]$dstpath)
     {
         ..\convspec $src $name -ver | as -o $dstpath\$name
         C:\msys64\usr\bin\objcopy -O binary -j .data $dstpath\$name $dstpath\$name
     }
     copy ..\otvdm.exe .
     copy ..\otvdmw.exe .
     copy ..\winhlp32.exe .
     copy ..\libwine.dll .
     copy ..\..\install.inf .
     copy ..\..\installw.inf
     copy ..\..\install.lnk .
     copy "..\install (no console).lnk" .
     copy ..\..\uninstall.reg .
     copy ..\..\otvdm.ini .
     copy ..\..\LICENSE .
     copy ..\..\README.md README.txt
     copy ..\*16 .
     copy ..\haxmvm.dll .
     copy ..\vm86.dll .
     copy ..\wow32.dll .
     mkdir WINDOWS
     mkdir WINDOWS\SYSTEM
     mkdir WINDOWS\SYSTEM32
     mkdir dummydll
     mkdir dummydll\SYSTEM
     mkdir dummydll\SYSTEM32
     ni WINDOWS\WIN.INI
     ni WINDOWS\SYSTEM.INI
     makedll "..\..\CTL3D\CTL3D.DLL16.SPEC" "CTL3D.DLL" "dummydll\SYSTEM"
     makedll "..\..\CTL3DV2\CTL3DV2.DLL16.SPEC" "CTL3DV2.DLL" "dummydll\SYSTEM"
     makedll "..\..\AVIFILE\AVIFILE.DLL16.SPEC" "AVIFILE.DLL" "dummydll\SYSTEM"
     makedll "..\..\COMM\COMM.DRV16.SPEC" "COMM.DRV" "dummydll\SYSTEM"
     makedll "..\..\COMMDLG\COMMDLG.DLL16.SPEC" "COMMDLG.DLL" "dummydll\SYSTEM"
     makedll "..\..\COMPOBJ\COMPOBJ.DLL16.SPEC" "COMPOBJ.DLL" "dummydll\SYSTEM"
     makedll "..\..\DDEML\DDEML.DLL16.SPEC" "DDEML.DLL" "dummydll\SYSTEM"
     makedll "..\..\DISPLAY\DISPLAY.DRV16.SPEC" "DISPLAY.DRV" "dummydll\SYSTEM"
     makedll "..\..\GDI\GDI.EXE16.SPEC" "GDI.EXE" "dummydll\SYSTEM"
     makedll "..\..\KEYBOARD\KEYBOARD.DRV16.SPEC" "KEYBOARD.DRV" "dummydll\SYSTEM"
     makedll "..\..\KRNL386\KRNL386.EXE16.SPEC" "KRNL386.EXE" "dummydll\SYSTEM"
     makedll "..\..\LZEXPAND\LZEXPAND.DLL16.SPEC" "LZEXPAND.DLL" "dummydll\SYSTEM"
     makedll "..\..\MMSYSTEM\MMSYSTEM.DLL16.SPEC" "MMSYSTEM.DLL" "dummydll\SYSTEM"
     makedll "..\..\MOUSE\MOUSE.DRV16.SPEC" "MOUSE.DRV" "dummydll\SYSTEM"
     makedll "..\..\MSACM\MSACM.DLL16.SPEC" "MSACM.DLL" "dummydll\SYSTEM"
     makedll "..\..\MSVIDEO\MSVIDEO.DLL16.SPEC" "MSVIDEO.DLL" "dummydll\SYSTEM"
     makedll "..\..\NDDEAPI\NDDEAPI.DLL16.SPEC" "NDDEAPI.DLL" "dummydll\SYSTEM"
     makedll "..\..\OLE2\OLE2.DLL16.SPEC" "OLE2.DLL" "dummydll\SYSTEM"
     makedll "..\..\OLE2CONV\OLE2CONV.DLL16.SPEC" "OLE2CONV.DLL" "dummydll\SYSTEM"
     makedll "..\..\OLE2DISP\OLE2DISP.DLL16.SPEC" "OLE2DISP.DLL" "dummydll\SYSTEM"
     makedll "..\..\OLE2NLS\OLE2NLS.DLL16.SPEC" "OLE2NLS.DLL" "dummydll\SYSTEM"
     makedll "..\..\OLE2PROX\OLE2PROX.DLL16.SPEC" "OLE2PROX.DLL" "dummydll\SYSTEM"
     makedll "..\..\OLE2THK\OLE2THK.DLL16.SPEC" "OLE2THK.DLL" "dummydll\SYSTEM"
     makedll "..\..\OLECLI\OLECLI.DLL16.SPEC" "OLECLI.DLL" "dummydll\SYSTEM"
     makedll "..\..\OLESVR\OLESVR.DLL16.SPEC" "OLESVR.DLL" "dummydll\SYSTEM"
     makedll "..\..\SHELL\SHELL.DLL16.SPEC" "SHELL.DLL" "dummydll\SYSTEM"
     makedll "..\..\SOUND\SOUND.DRV16.SPEC" "SOUND.DRV" "dummydll\SYSTEM"
     makedll "..\..\STORAGE\STORAGE.DLL16.SPEC" "STORAGE.DLL" "dummydll\SYSTEM"
     makedll "..\..\SYSTEM\SYSTEM.DRV16.SPEC" "SYSTEM.DRV" "dummydll\SYSTEM"
     makedll "..\..\TOOLHELP\TOOLHELP.DLL16.SPEC" "TOOLHELP.DLL" "dummydll\SYSTEM"
     makedll "..\..\USER\USER.EXE16.SPEC" "USER.EXE" "dummydll\SYSTEM"
     makedll "..\..\VER\VER.DLL16.SPEC" "VER.DLL" "dummydll\SYSTEM"
     makedll "..\..\WIFEMAN\WIFEMAN.DLL16.SPEC" "WIFEMAN.DLL" "dummydll\SYSTEM"
     makedll "..\..\WIN87EM\WIN87EM.DLL16.SPEC" "WIN87EM.DLL" "dummydll\SYSTEM"
     makedll "..\..\WING\WING.DLL16.SPEC" "WING.DLL" "dummydll\SYSTEM"
     makedll "..\..\WINNLS\WINNLS.DLL16.SPEC" "WINNLS.DLL" "dummydll\SYSTEM"
     makedll "..\..\WINOLDAP\WINOLDAP.MOD16.SPEC" "WINOLDAP.MOD" "dummydll\SYSTEM"
     makedll "..\..\WINSOCK\WINSOCK.DLL16.SPEC" "WINSOCK.DLL" "dummydll\SYSTEM"
     makedll "..\..\WINSPOOL\WINSPOOL.DRV16.SPEC" "WINSPOOL.DRV" "dummydll\SYSTEM"
     copy ..\..\dummydll\dummydll.dll WINDOWS\SYSTEM\KRNL286.EXE
     copy ..\..\dummydll\dummydll.dll WINDOWS\SYSTEM\VGA.DRV
     copy ..\..\dummydll\dummydll.dll WINDOWS\SYSTEM32\WOWEXEC.EXE
     makedll "..\..\CTL3D\CTL3D.DLL16.SPEC" "CTL3D.DLL" "WINDOWS\SYSTEM"
     makedll "..\..\CTL3DV2\CTL3DV2.DLL16.SPEC" "CTL3DV2.DLL" "WINDOWS\SYSTEM"
     makedll "..\..\AVIFILE\AVIFILE.DLL16.SPEC" "AVIFILE.DLL" "WINDOWS\SYSTEM"
     makedll "..\..\COMM\COMM.DRV16.SPEC" "COMM.DRV" "WINDOWS\SYSTEM"
     makedll "..\..\COMMDLG\COMMDLG.DLL16.SPEC" "COMMDLG.DLL" "WINDOWS\SYSTEM"
     makedll "..\..\COMPOBJ\COMPOBJ.DLL16.SPEC" "COMPOBJ.DLL" "WINDOWS\SYSTEM"
     makedll "..\..\DDEML\DDEML.DLL16.SPEC" "DDEML.DLL" "WINDOWS\SYSTEM"
     makedll "..\..\DISPLAY\DISPLAY.DRV16.SPEC" "DISPLAY.DRV" "WINDOWS\SYSTEM"
     makedll "..\..\GDI\GDI.EXE16.SPEC" "GDI.EXE" "WINDOWS\SYSTEM"
     makedll "..\..\KEYBOARD\KEYBOARD.DRV16.SPEC" "KEYBOARD.DRV" "WINDOWS\SYSTEM"
     makedll "..\..\KRNL386\KRNL386.EXE16.SPEC" "KRNL386.EXE" "WINDOWS\SYSTEM"
     makedll "..\..\LZEXPAND\LZEXPAND.DLL16.SPEC" "LZEXPAND.DLL" "WINDOWS\SYSTEM"
     makedll "..\..\MMSYSTEM\MMSYSTEM.DLL16.SPEC" "MMSYSTEM.DLL" "WINDOWS\SYSTEM"
     makedll "..\..\MOUSE\MOUSE.DRV16.SPEC" "MOUSE.DRV" "WINDOWS\SYSTEM"
     makedll "..\..\MSACM\MSACM.DLL16.SPEC" "MSACM.DLL" "WINDOWS\SYSTEM"
     makedll "..\..\MSVIDEO\MSVIDEO.DLL16.SPEC" "MSVIDEO.DLL" "WINDOWS\SYSTEM"
     makedll "..\..\NDDEAPI\NDDEAPI.DLL16.SPEC" "NDDEAPI.DLL" "WINDOWS\SYSTEM"
     makedll "..\..\OLE2\OLE2.DLL16.SPEC" "OLE2.DLL" "WINDOWS\SYSTEM"
     makedll "..\..\OLE2CONV\OLE2CONV.DLL16.SPEC" "OLE2CONV.DLL" "WINDOWS\SYSTEM"
     makedll "..\..\OLE2DISP\OLE2DISP.DLL16.SPEC" "OLE2DISP.DLL" "WINDOWS\SYSTEM"
     makedll "..\..\OLE2NLS\OLE2NLS.DLL16.SPEC" "OLE2NLS.DLL" "WINDOWS\SYSTEM"
     makedll "..\..\OLE2PROX\OLE2PROX.DLL16.SPEC" "OLE2PROX.DLL" "WINDOWS\SYSTEM"
     makedll "..\..\OLE2THK\OLE2THK.DLL16.SPEC" "OLE2THK.DLL" "WINDOWS\SYSTEM"
     makedll "..\..\OLECLI\OLECLI.DLL16.SPEC" "OLECLI.DLL" "WINDOWS\SYSTEM"
     makedll "..\..\OLESVR\OLESVR.DLL16.SPEC" "OLESVR.DLL" "WINDOWS\SYSTEM"
     makedll "..\..\SHELL\SHELL.DLL16.SPEC" "SHELL.DLL" "WINDOWS\SYSTEM"
     makedll "..\..\SOUND\SOUND.DRV16.SPEC" "SOUND.DRV" "WINDOWS\SYSTEM"
     makedll "..\..\STORAGE\STORAGE.DLL16.SPEC" "STORAGE.DLL" "WINDOWS\SYSTEM"
     makedll "..\..\SYSTEM\SYSTEM.DRV16.SPEC" "SYSTEM.DRV" "WINDOWS\SYSTEM"
     makedll "..\..\TOOLHELP\TOOLHELP.DLL16.SPEC" "TOOLHELP.DLL" "WINDOWS\SYSTEM"
     makedll "..\..\USER\USER.EXE16.SPEC" "USER.EXE" "WINDOWS\SYSTEM"
     makedll "..\..\VER\VER.DLL16.SPEC" "VER.DLL" "WINDOWS\SYSTEM"
     makedll "..\..\WIFEMAN\WIFEMAN.DLL16.SPEC" "WIFEMAN.DLL" "WINDOWS\SYSTEM"
     makedll "..\..\WIN87EM\WIN87EM.DLL16.SPEC" "WIN87EM.DLL" "WINDOWS\SYSTEM"
     makedll "..\..\WING\WING.DLL16.SPEC" "WING.DLL" "WINDOWS\SYSTEM"
     makedll "..\..\WINNLS\WINNLS.DLL16.SPEC" "WINNLS.DLL" "WINDOWS\SYSTEM"
     makedll "..\..\WINOLDAP\WINOLDAP.MOD16.SPEC" "WINOLDAP.MOD" "WINDOWS\SYSTEM"
     makedll "..\..\WINSOCK\WINSOCK.DLL16.SPEC" "WINSOCK.DLL" "WINDOWS\SYSTEM"
     makedll "..\..\WINSPOOL\WINSPOOL.DRV16.SPEC" "WINSPOOL.DRV" "WINDOWS\SYSTEM"
     copy ..\..\dummydll\dummydll.dll WINDOWS\SYSTEM\KRNL286.EXE
     copy ..\..\dummydll\dummydll.dll WINDOWS\SYSTEM\VGA.DRV
     copy ..\..\dummydll\dummydll.dll WINDOWS\SYSTEM32\WOWEXEC.EXE
     copy C:\msys64\mingw32\bin\libgcc_s_dw2-1.dll .
     copy C:\msys64\mingw32\bin\libstdc++-6.dll .
     copy C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin\libwinpthread-1.dll .
     cd ..
     7z a otvdm-cmake-gcc-${env:APPVEYOR_REPO_BRANCH}-${env:APPVEYOR_BUILD_NUMBER}.zip otvdm-cmake-gcc-${env:APPVEYOR_REPO_BRANCH}-${env:APPVEYOR_BUILD_NUMBER}
     move otvdm-cmake-gcc-${env:APPVEYOR_REPO_BRANCH}-${env:APPVEYOR_BUILD_NUMBER}.zip ..

-
  matrix:
    only:
      - THIS_BUILD_IS_RECOMMENDED__VCXPROJ_BUILD: 1
  before_build:
    ps: |
      C:\msys64\usr\bin\as --version
      echo "<?xml version=""1.0"" encoding=""utf-8""?>
      <Project ToolsVersion=""4.0"" xmlns=""http://schemas.microsoft.com/developer/msbuild/2003"">
        <ImportGroup Label=""PropertySheets"" />
        <PropertyGroup Label=""UserMacros"">
          <AsmPath>C:\msys64\usr\bin\</AsmPath>
          <NtDllLibPath>`$(UniversalCRTSdkDir)Lib\10.0.17134.0\um\x86\</NtDllLibPath>
        </PropertyGroup>
        <PropertyGroup>
          <_PropertySheetDisplayName>MacroPropertySheet</_PropertySheetDisplayName>
          <IncludePath>`$(SolutionDir)wow32;`$(IncludePath)</IncludePath>
        </PropertyGroup>
        <ItemDefinitionGroup>
          <ClCompile>
            <RuntimeLibrary>MultiThreadedDLL</RuntimeLibrary>
            <PreprocessorDefinitions>__CI_VERSION=${env:APPVEYOR_BUILD_NUMBER};%(PreprocessorDefinitions)</PreprocessorDefinitions>
            <WarningLevel>TurnOffAllWarnings</WarningLevel>
          </ClCompile>
        </ItemDefinitionGroup>
        <ItemGroup>
          <BuildMacro Include=""AsmPath"">
            <Value>`$(AsmPath)</Value>
          </BuildMacro>
          <BuildMacro Include=""NtDllLibPath"">
            <Value>`$(NtDllLibPath)</Value>
          </BuildMacro>
        </ItemGroup>
      </Project>
      " > C:\projects\winevdm\PropertySheet.props

  before_package:
    ps: |
      cd Release
      del *.ilk
      del *.lib
      del *.pdb
      del *.exp
      del *.map
      del *.iobj
      del *.ipdb
      del widl.exe
      del convertwinefile.exe
      copy ..\install.inf .
      copy ..\installw.inf .
      copy ..\install.lnk .
      copy "..\install (no console).lnk" .
      copy ..\uninstall.reg .
      copy ..\otvdm.ini .
      copy ..\LICENSE .
      copy ..\README.md .\README.txt
      mkdir dll
      move *16 dll
      move haxmvm.dll dll
      move vm86.dll dll
      move wow32.dll dll
      If (${env:APPVEYOR_REPO_BRANCH} -eq "winxp")
      {
        del dll\haxmvm.dll
        move dll\wow32.dll .
        move dll\vm86.dll .
        move dll\*.drv16 .
        move dll\krnl386.exe16 .
        move dll\user.exe16 .
        move dll\gdi.exe16 .
        move dll\ctl3dv2.dll16 .
        move dll\ctl3d.dll16 .
        move dll\mmsystem.dll16 .
        move dll\winnls.dll16 .
      }
      function makedll([string]$src, [string]$name, [string]$dstpath)
      {
        .\convspec $src $name -ver | C:\msys64\usr\bin\as -o $dstpath\$name
        C:\msys64\usr\bin\objcopy -O binary -j .data $dstpath\$name $dstpath\$name
      }
      mkdir WINDOWS
      mkdir WINDOWS\SYSTEM
      mkdir WINDOWS\SYSTEM32
      ni WINDOWS\WIN.INI
      ni WINDOWS\SYSTEM.INI
      mkdir dummydll
      mkdir dummydll\SYSTEM
      mkdir dummydll\SYSTEM32
      makedll "..\CTL3D\CTL3D.DLL16.SPEC" "CTL3D.DLL" "dummydll\SYSTEM"
      makedll "..\CTL3DV2\CTL3DV2.DLL16.SPEC" "CTL3DV2.DLL" "dummydll\SYSTEM"
      makedll "..\AVIFILE\AVIFILE.DLL16.SPEC" "AVIFILE.DLL" "dummydll\SYSTEM"
      makedll "..\COMM\COMM.DRV16.SPEC" "COMM.DRV" "dummydll\SYSTEM"
      makedll "..\COMMDLG\COMMDLG.DLL16.SPEC" "COMMDLG.DLL" "dummydll\SYSTEM"
      makedll "..\COMPOBJ\COMPOBJ.DLL16.SPEC" "COMPOBJ.DLL" "dummydll\SYSTEM"
      makedll "..\DDEML\DDEML.DLL16.SPEC" "DDEML.DLL" "dummydll\SYSTEM"
      makedll "..\DISPLAY\DISPLAY.DRV16.SPEC" "DISPLAY.DRV" "dummydll\SYSTEM"
      makedll "..\GDI\GDI.EXE16.SPEC" "GDI.EXE" "dummydll\SYSTEM"
      makedll "..\KEYBOARD\KEYBOARD.DRV16.SPEC" "KEYBOARD.DRV" "dummydll\SYSTEM"
      makedll "..\KRNL386\KRNL386.EXE16.SPEC" "KRNL386.EXE" "dummydll\SYSTEM"
      makedll "..\LZEXPAND\LZEXPAND.DLL16.SPEC" "LZEXPAND.DLL" "dummydll\SYSTEM"
      makedll "..\MMSYSTEM\MMSYSTEM.DLL16.SPEC" "MMSYSTEM.DLL" "dummydll\SYSTEM"
      makedll "..\MOUSE\MOUSE.DRV16.SPEC" "MOUSE.DRV" "dummydll\SYSTEM"
      makedll "..\MSACM\MSACM.DLL16.SPEC" "MSACM.DLL" "dummydll\SYSTEM"
      makedll "..\MSVIDEO\MSVIDEO.DLL16.SPEC" "MSVIDEO.DLL" "dummydll\SYSTEM"
      makedll "..\NDDEAPI\NDDEAPI.DLL16.SPEC" "NDDEAPI.DLL" "dummydll\SYSTEM"
      makedll "..\OLE2\OLE2.DLL16.SPEC" "OLE2.DLL" "dummydll\SYSTEM"
      makedll "..\OLE2CONV\OLE2CONV.DLL16.SPEC" "OLE2CONV.DLL" "dummydll\SYSTEM"
      makedll "..\OLE2DISP\OLE2DISP.DLL16.SPEC" "OLE2DISP.DLL" "dummydll\SYSTEM"
      makedll "..\OLE2NLS\OLE2NLS.DLL16.SPEC" "OLE2NLS.DLL" "dummydll\SYSTEM"
      makedll "..\OLE2PROX\OLE2PROX.DLL16.SPEC" "OLE2PROX.DLL" "dummydll\SYSTEM"
      makedll "..\OLE2THK\OLE2THK.DLL16.SPEC" "OLE2THK.DLL" "dummydll\SYSTEM"
      makedll "..\OLECLI\OLECLI.DLL16.SPEC" "OLECLI.DLL" "dummydll\SYSTEM"
      makedll "..\OLESVR\OLESVR.DLL16.SPEC" "OLESVR.DLL" "dummydll\SYSTEM"
      makedll "..\SHELL\SHELL.DLL16.SPEC" "SHELL.DLL" "dummydll\SYSTEM"
      makedll "..\SOUND\SOUND.DRV16.SPEC" "SOUND.DRV" "dummydll\SYSTEM"
      makedll "..\STORAGE\STORAGE.DLL16.SPEC" "STORAGE.DLL" "dummydll\SYSTEM"
      makedll "..\SYSTEM\SYSTEM.DRV16.SPEC" "SYSTEM.DRV" "dummydll\SYSTEM"
      makedll "..\TOOLHELP\TOOLHELP.DLL16.SPEC" "TOOLHELP.DLL" "dummydll\SYSTEM"
      makedll "..\USER\USER.EXE16.SPEC" "USER.EXE" "dummydll\SYSTEM"
      makedll "..\VER\VER.DLL16.SPEC" "VER.DLL" "dummydll\SYSTEM"
      makedll "..\WIFEMAN\WIFEMAN.DLL16.SPEC" "WIFEMAN.DLL" "dummydll\SYSTEM"
      makedll "..\WIN87EM\WIN87EM.DLL16.SPEC" "WIN87EM.DLL" "dummydll\SYSTEM"
      makedll "..\WING\WING.DLL16.SPEC" "WING.DLL" "dummydll\SYSTEM"
      makedll "..\WINNLS\WINNLS.DLL16.SPEC" "WINNLS.DLL" "dummydll\SYSTEM"
      makedll "..\WINOLDAP\WINOLDAP.MOD16.SPEC" "WINOLDAP.MOD" "dummydll\SYSTEM"
      makedll "..\WINSOCK\WINSOCK.DLL16.SPEC" "WINSOCK.DLL" "dummydll\SYSTEM"
      makedll "..\WINSPOOL\WINSPOOL.DRV16.SPEC" "WINSPOOL.DRV" "dummydll\SYSTEM"
      copy ..\dummydll\dummydll.dll WINDOWS\SYSTEM\KRNL286.EXE
      copy ..\dummydll\dummydll.dll WINDOWS\SYSTEM\VGA.DRV
      copy ..\dummydll\dummydll.dll WINDOWS\SYSTEM32\WOWEXEC.EXE
      makedll "..\CTL3D\CTL3D.DLL16.SPEC" "CTL3D.DLL" "WINDOWS\SYSTEM"
      makedll "..\CTL3DV2\CTL3DV2.DLL16.SPEC" "CTL3DV2.DLL" "WINDOWS\SYSTEM"
      makedll "..\AVIFILE\AVIFILE.DLL16.SPEC" "AVIFILE.DLL" "WINDOWS\SYSTEM"
      makedll "..\COMM\COMM.DRV16.SPEC" "COMM.DRV" "WINDOWS\SYSTEM"
      makedll "..\COMMDLG\COMMDLG.DLL16.SPEC" "COMMDLG.DLL" "WINDOWS\SYSTEM"
      makedll "..\COMPOBJ\COMPOBJ.DLL16.SPEC" "COMPOBJ.DLL" "WINDOWS\SYSTEM"
      makedll "..\DDEML\DDEML.DLL16.SPEC" "DDEML.DLL" "WINDOWS\SYSTEM"
      makedll "..\DISPLAY\DISPLAY.DRV16.SPEC" "DISPLAY.DRV" "WINDOWS\SYSTEM"
      makedll "..\GDI\GDI.EXE16.SPEC" "GDI.EXE" "WINDOWS\SYSTEM"
      makedll "..\KEYBOARD\KEYBOARD.DRV16.SPEC" "KEYBOARD.DRV" "WINDOWS\SYSTEM"
      makedll "..\KRNL386\KRNL386.EXE16.SPEC" "KRNL386.EXE" "WINDOWS\SYSTEM"
      makedll "..\LZEXPAND\LZEXPAND.DLL16.SPEC" "LZEXPAND.DLL" "WINDOWS\SYSTEM"
      makedll "..\MMSYSTEM\MMSYSTEM.DLL16.SPEC" "MMSYSTEM.DLL" "WINDOWS\SYSTEM"
      makedll "..\MOUSE\MOUSE.DRV16.SPEC" "MOUSE.DRV" "WINDOWS\SYSTEM"
      makedll "..\MSACM\MSACM.DLL16.SPEC" "MSACM.DLL" "WINDOWS\SYSTEM"
      makedll "..\MSVIDEO\MSVIDEO.DLL16.SPEC" "MSVIDEO.DLL" "WINDOWS\SYSTEM"
      makedll "..\NDDEAPI\NDDEAPI.DLL16.SPEC" "NDDEAPI.DLL" "WINDOWS\SYSTEM"
      makedll "..\OLE2\OLE2.DLL16.SPEC" "OLE2.DLL" "WINDOWS\SYSTEM"
      makedll "..\OLE2CONV\OLE2CONV.DLL16.SPEC" "OLE2CONV.DLL" "WINDOWS\SYSTEM"
      makedll "..\OLE2DISP\OLE2DISP.DLL16.SPEC" "OLE2DISP.DLL" "WINDOWS\SYSTEM"
      makedll "..\OLE2NLS\OLE2NLS.DLL16.SPEC" "OLE2NLS.DLL" "WINDOWS\SYSTEM"
      makedll "..\OLE2PROX\OLE2PROX.DLL16.SPEC" "OLE2PROX.DLL" "WINDOWS\SYSTEM"
      makedll "..\OLE2THK\OLE2THK.DLL16.SPEC" "OLE2THK.DLL" "WINDOWS\SYSTEM"
      makedll "..\OLECLI\OLECLI.DLL16.SPEC" "OLECLI.DLL" "WINDOWS\SYSTEM"
      makedll "..\OLESVR\OLESVR.DLL16.SPEC" "OLESVR.DLL" "WINDOWS\SYSTEM"
      makedll "..\SHELL\SHELL.DLL16.SPEC" "SHELL.DLL" "WINDOWS\SYSTEM"
      makedll "..\SOUND\SOUND.DRV16.SPEC" "SOUND.DRV" "WINDOWS\SYSTEM"
      makedll "..\STORAGE\STORAGE.DLL16.SPEC" "STORAGE.DLL" "WINDOWS\SYSTEM"
      makedll "..\SYSTEM\SYSTEM.DRV16.SPEC" "SYSTEM.DRV" "WINDOWS\SYSTEM"
      makedll "..\TOOLHELP\TOOLHELP.DLL16.SPEC" "TOOLHELP.DLL" "WINDOWS\SYSTEM"
      makedll "..\USER\USER.EXE16.SPEC" "USER.EXE" "WINDOWS\SYSTEM"
      makedll "..\VER\VER.DLL16.SPEC" "VER.DLL" "WINDOWS\SYSTEM"
      makedll "..\WIFEMAN\WIFEMAN.DLL16.SPEC" "WIFEMAN.DLL" "WINDOWS\SYSTEM"
      makedll "..\WIN87EM\WIN87EM.DLL16.SPEC" "WIN87EM.DLL" "WINDOWS\SYSTEM"
      makedll "..\WING\WING.DLL16.SPEC" "WING.DLL" "WINDOWS\SYSTEM"
      makedll "..\WINNLS\WINNLS.DLL16.SPEC" "WINNLS.DLL" "WINDOWS\SYSTEM"
      makedll "..\WINOLDAP\WINOLDAP.MOD16.SPEC" "WINOLDAP.MOD" "WINDOWS\SYSTEM"
      makedll "..\WINSOCK\WINSOCK.DLL16.SPEC" "WINSOCK.DLL" "WINDOWS\SYSTEM"
      makedll "..\WINSPOOL\WINSPOOL.DRV16.SPEC" "WINSPOOL.DRV" "WINDOWS\SYSTEM"
      copy ..\dummydll\dummydll.dll WINDOWS\SYSTEM\KRNL286.EXE
      copy ..\dummydll\dummydll.dll WINDOWS\SYSTEM\VGA.DRV
      copy ..\dummydll\dummydll.dll WINDOWS\SYSTEM32\WOWEXEC.EXE
      del convspec.exe
      cd ..
      rename-item Release otvdm-${env:APPVEYOR_REPO_BRANCH}-${env:APPVEYOR_BUILD_NUMBER}
      7z a otvdm-${env:APPVEYOR_REPO_BRANCH}-${env:APPVEYOR_BUILD_NUMBER}.zip otvdm-${env:APPVEYOR_REPO_BRANCH}-${env:APPVEYOR_BUILD_NUMBER}

artifacts:
- path: '*.zip'
  name: otvdm-Debug
